### ISSUE TITLE
Blinking graph & watch recognition

### ISSUE THREAD

**Issue by netol** [jimmykane/quantified-self#127]
- when moving with cursor above the HR/altitude/pace/whatever graph, only the labels show, the graph itself disappears (Mozilla ers 60.5)
- fit file imported from Movescount does not recognize Suunto Spartan Sport (=Suunto Unknown) (it does recognize A3P and A3V)

**Comment by jimmykane** [comment]
Would you be so kind as to attach the fit file from the SSS? 
Usually, those watches are represented with an integer and depending on manufacturer it's kinda a wild guess so far.

**Comment by netol** [comment]
Sure, the file should be enclosed to this comment. (Anyway - good job with your service, thanks!)

https://quantified-self.io/user/C5i9cO6dm9gEc3p9QUKoLhiXqyY2/event/kjXRl9ZTAgAcQjGbJuSw

[Move_2018_12_31_22_31_03_Trail_running.zip](https://github.com/jimmykane/quantified-self/files/2857690/Move_2018_12_31_22_31_03_Trail_running.zip)

**Comment by jimmykane** [comment]
Version 2.0.44-MFF73 is being deployed that fixes the blinking

**Comment by jimmykane** [comment]
Version 2.0.44-MFF73 is now live

**Comment by jimmykane** [comment]
2.0.45-MFF73 adds the 28 integers for fit file that is mapped to the model of "Brighton" aka Suunto Spartan Sport 

Version 2.0.45-MFF73is deployed atm but reimport might be necessary. At the point of the import, the device name is persisted as a string if that is found. If not there are so many providers that a single string is not sufficient or any other type. 

I ll go ahead and wait for your confirmation that these 2 issues are closed now @netol

**Comment by netol** [comment]
Thanks, both issues can be closed now.
