### ISSUE TITLE
Sync merged activites based on time

### ISSUE THREAD

**Issue by garagenisse** [jimmykane/quantified-self#137]
If i import two activity files from two sensors based on one real activity and then merge them is it possible to syncronize them in time in merged view?

![image](https://user-images.githubusercontent.com/3446623/55219349-0133d900-5205-11e9-9c56-c7d197aad274.png)

**Comment by jimmykane** [comment]
Hey hi @garagenisse  would you like to provide a link or the files? 
You can via Quantified self share the url just makle sure before the merge is made public

**Comment by garagenisse** [comment]
Hi, no problems, hope you can see this:

Merged:
https://quantified-self.io/user/6xkZ2qfuJ0gczlfsdeJJXGndhDJ2/event/5ekFqD7ZMeVgDwiVhl6u

Power 1:
https://quantified-self.io/user/6xkZ2qfuJ0gczlfsdeJJXGndhDJ2/event/0r61Em48yv1HruFytyCQ

Power 2:
https://quantified-self.io/user/6xkZ2qfuJ0gczlfsdeJJXGndhDJ2/event/BCQ8GmXT9adjJlA4hXsL

**Comment by jimmykane** [comment]
I see the issue. That is because the app uses the duration as the xAxis.
You can chnage that though. Go to your profile and then settings and switch
to time. That will align the charts bases on absolute time.


Tell me if it worked

**Comment by garagenisse** [comment]
Ah, my bad, thats perfect! Awesome tool!

Regards Andreas
