### ISSUE TITLE
Strava GPX error : Some files could not be processed

### ISSUE THREAD

**Issue by Pieter-ZA** [jimmykane/quantified-self#138]
Importing certain (Polar Vantage M) GPX files from Strava GPX export throw 'Some files could not be processed'
[Bronberrick_Parkrun (1).zip](https://github.com/jimmykane/quantified-self/files/3027829/Bronberrick_Parkrun.1.zip)

**Comment by jimmykane** [comment]
Hey thanks. Ill look into it asap

**Comment by jimmykane** [comment]
v2.1.16 should be now live on https://quantified-self.io/home 

Fixes this regression issue. Sorry, another fix had brought this little bug and thanks a lot for spotting that out!

**Comment by Pieter-ZA** [comment]
Many thanks, much appreciated! 👍 :)

**Comment by Pieter-ZA** [comment]
Thanks!

Kind regards

Pieter Oosthuizen
