### ISSUE TITLE
X axis values are weird

### ISSUE THREAD

**Issue by Djailla** [jimmykane/quantified-self#140]
The units for time on the X axis are strange, starting at 23:00 to ???

<img width="1786" alt="Capture d’écran 2019-04-17 à 14 30 52" src="https://user-images.githubusercontent.com/576608/56290148-cb5a8400-6122-11e9-9579-d1d1abd68059.png">

**Comment by jimmykane** [comment]
Version 2.2.0-Bastien fixes this
