### ISSUE TITLE
Does Not Compile on macOS 10.14.4

### ISSUE THREAD

**Issue by NordicFlyer** [jimmykane/quantified-self#145]
The latest 2.2.3 Veldkip fails to build utilizing either NPM or YARN based on instructions in readme file. Any solution?

it fails to build as follows:

ERROR in ./node_modules/@amcharts/amcharts4/.internal/core/export/Export.js 67:24
Module parse failed: Unexpected token (67:24)
You may need an appropriate loader to handle this file type.
|             switch (_a.label) {
|                 case 0: return [4 /*yield*/, Promise.all([
>                         import(/* webpackChunkName: "pdfmake" */ "pdfmake/build/pdfmake.js"),
|                         import(/* webpackChunkName: "pdfmake" */ "../../pdfmake/vfs_fonts")
|                     ])];
ℹ ｢wdm｣: Failed to compile.

The last known version to successfully build was quantified-self-2.2.1-Bastien.

**Comment by jimmykane** [comment]
Could you clear the node modules and try again with yarn ? I'll take a look
tomorrow as well.

**Comment by jimmykane** [comment]
I took a look and could install and run the app with a clean clone  and using YARN. 

However since I know the wepback issue with NPM here is a package JSON that should solve your problem if you still use NPM 

```
{
  "name": "quantified-self",
  "version": "2.2.1-Bastien",
  "license": "SEE LICENSE IN LICENSE.md",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build --verbose",
    "build-production": "ng build --verbose --prod",
    "deploy": "firebase deploy",
    "build-and-deploy-prod": "npm run build-production && npm run deploy",
    "build-and-deploy-dev": "npm run build && npm run deploy",
    "test": "ng test",
    "test-coverage": "ng test --code-coverage",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@agm/core": "^1.0.0-beta.5",
    "@amcharts/amcharts4": "4.4.0",
    "@angular/animations": "7.2.13",
    "@angular/cdk": "^7.3.7",
    "@angular/common": "7.2.13",
    "@angular/compiler": "7.2.13",
    "@angular/core": "7.2.13",
    "@angular/fire": "^5.1.2",
    "@angular/forms": "7.2.13",
    "@angular/http": "7.2.13",
    "@angular/material": "^7.3.7",
    "@angular/platform-browser": "7.2.13",
    "@angular/platform-browser-dynamic": "7.2.13",
    "@angular/platform-server": "7.2.13",
    "@angular/router": "7.2.13",
    "@types/pako": "^1.0.1",
    "@types/uuid": "^3.4.4",
    "angular2-fontawesome": "^5.2.1",
    "core-js": "^2.6.5",
    "firebase": "^5.9.4",
    "font-awesome": "^4.7.0",
    "hammerjs": "^2.0.8",
    "material-design-icons": "^3.0.1",
    "ng2-logger": "2.0.48",
    "quantified-self-lib": "github:jimmykane/quantified-self-lib#feature/streams-pub",
    "raven-js": "^3.27.0",
    "roboto-fontface": "^0.10.0",
    "rxjs": "^6.4.0",
    "yarn": "^1.15.2",
    "zone.js": "^0.9.0"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.13.8",
    "@angular/cli": "7.3.8",
    "@angular/compiler-cli": "7.2.13",
    "@types/jasmine": "3.3.12",
    "@types/node": "^11.13.4",
    "codelyzer": "~5.0.0",
    "jasmine-core": "^3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-cli": "~2.0.0",
    "karma-coverage-istanbul-reporter": "^2.0.5",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "~6.0.0",
    "ts-node": "~8.1.0",
    "tslint": "~5.16.0",
    "typescript": "3.2.4"
  }
}

```

Don't forget to pull also the latest changes and then replace the package.json

**Comment by NordicFlyer** [comment]
> I took a look and could install and run the app with a clean clone and using YARN.
> 
> However since I know the wepback issue with NPM here is a package JSON that should solve your problem if you still use NPM
> 
> ```
> {
>   "name": "quantified-self",
>   "version": "2.2.1-Bastien",
>   "license": "SEE LICENSE IN LICENSE.md",
>   "scripts": {
>     "ng": "ng",
>     "start": "ng serve",
>     "build": "ng build --verbose",
>     "build-production": "ng build --verbose --prod",
>     "deploy": "firebase deploy",
>     "build-and-deploy-prod": "npm run build-production && npm run deploy",
>     "build-and-deploy-dev": "npm run build && npm run deploy",
>     "test": "ng test",
>     "test-coverage": "ng test --code-coverage",
>     "lint": "ng lint",
>     "e2e": "ng e2e"
>   },
>   "private": true,
>   "dependencies": {
>     "@agm/core": "^1.0.0-beta.5",
>     "@amcharts/amcharts4": "4.4.0",
>     "@angular/animations": "7.2.13",
>     "@angular/cdk": "^7.3.7",
>     "@angular/common": "7.2.13",
>     "@angular/compiler": "7.2.13",
>     "@angular/core": "7.2.13",
>     "@angular/fire": "^5.1.2",
>     "@angular/forms": "7.2.13",
>     "@angular/http": "7.2.13",
>     "@angular/material": "^7.3.7",
>     "@angular/platform-browser": "7.2.13",
>     "@angular/platform-browser-dynamic": "7.2.13",
>     "@angular/platform-server": "7.2.13",
>     "@angular/router": "7.2.13",
>     "@types/pako": "^1.0.1",
>     "@types/uuid": "^3.4.4",
>     "angular2-fontawesome": "^5.2.1",
>     "core-js": "^2.6.5",
>     "firebase": "^5.9.4",
>     "font-awesome": "^4.7.0",
>     "hammerjs": "^2.0.8",
>     "material-design-icons": "^3.0.1",
>     "ng2-logger": "2.0.48",
>     "quantified-self-lib": "github:jimmykane/quantified-self-lib#feature/streams-pub",
>     "raven-js": "^3.27.0",
>     "roboto-fontface": "^0.10.0",
>     "rxjs": "^6.4.0",
>     "yarn": "^1.15.2",
>     "zone.js": "^0.9.0"
>   },
>   "devDependencies": {
>     "@angular-devkit/build-angular": "~0.13.8",
>     "@angular/cli": "7.3.8",
>     "@angular/compiler-cli": "7.2.13",
>     "@types/jasmine": "3.3.12",
>     "@types/node": "^11.13.4",
>     "codelyzer": "~5.0.0",
>     "jasmine-core": "^3.4.0",
>     "jasmine-spec-reporter": "~4.2.1",
>     "karma": "~4.1.0",
>     "karma-chrome-launcher": "~2.2.0",
>     "karma-cli": "~2.0.0",
>     "karma-coverage-istanbul-reporter": "^2.0.5",
>     "karma-jasmine": "~2.0.1",
>     "karma-jasmine-html-reporter": "^1.4.0",
>     "protractor": "~6.0.0",
>     "ts-node": "~8.1.0",
>     "tslint": "~5.16.0",
>     "typescript": "3.2.4"
>   }
> }
> ```
> Don't forget to pull also the latest changes and then replace the package.json

I just cannot get 2.2.3-Veldkip to install (npm install) and compile (npm start) without errors. I tried your suggestion(s) and replaced the package.json with the code provided (why 2.2.1-Bastien??) and it still failed to compile. I started again with a fresh clone of 2.2.3-Veldkip and used yarn instead. I ran into a timeout error over and over again. This seemed to solve that problem: 'yarn install --network-timeout 1000000' but with install warnings and compile problems. Attached is the
[yarn install and start.pdf](https://github.com/jimmykane/quantified-self/files/3125528/yarn.install.and.start.pdf)
 terminal output (pdf):

**Comment by jimmykane** [comment]
I see the issue. I need to patch a dependent local lib. Give me a few and thanks a lot for the effort

**Comment by jimmykane** [comment]
Btw `why 2.2.1-Bastien` I name versions after people who contribute. I bet next one should have your name :-)

**Comment by jimmykane** [comment]
I just pushed 2.2.4-Veldkip that should solve your compile issues.

**Comment by NordicFlyer** [comment]
> I just pushed 2.2.4-Veldkip that should solve your compile issues.

Still issues. Will not compile via Yarn unless I comment out the code where the error occurs.
i.e. src/app/components/cards/event/devices/event.card.devices.component.ts
`getData(activity: ActivityInterface) {
    return new MatTableDataSource(activity.creator.devices.reduce((deviceDataArray, device, index) => {
      const deviceObject = {
        '#': index + 1,
        'Type': device.type,
        **// 'Name': device.name,**
        'Battery Status': device.batteryStatus,
        // 'batteryVoltage': device.batteryVoltage,
        'Manufacturer': device.manufacturer,
        // 'serialNumber': device.serialNumber,
        'Product': device.product,
        'Software Info': device.swInfo,
        // 'hwInfo': device.hwInfo,
        'Ant Device Number': device.antDeviceNumber,
        // 'antTransmissionType': device.antTransmissionType,
        // 'antNetwork': device.antNetwork,
        // 'sourceType': device.sourceType,
        // 'cumOperatingTime': device.cumOperatingTime,
      };`
[compile fail_terminal output.txt](https://github.com/jimmykane/quantified-self/files/3129299/compile.fail_terminal.output.txt)

**Comment by NordicFlyer** [comment]
> Btw `why 2.2.1-Bastien` I name versions after people who contribute. I bet next one should have your name :-)

I would be honoured! Thanks for all your work in creating such a useful application. I have some ideas/suggestions on implementing many features but will send you a private email on the aforementioned. Thanks.

**Comment by jimmykane** [comment]
Looks much better I think one last issue to fix from one lib. Give me a few
hours to have that done.

**Comment by jimmykane** [comment]
Hey are you sure you have 2.2.4-Veldkip ? 

I just tried and looks fine. The error shows some old lib is not installed. Please try with a new folder and if that does not help try deleting the `yarn.lock` file.

**Comment by NordicFlyer** [comment]
> Hey are you sure you have 2.2.4-Veldkip ?
> 
> I just tried and looks fine. The error shows some old lib is not installed. Please try with a new folder and if that does not help try deleting the `yarn.lock` file.

Yes...I use git clone and cloned it from the master - npm install works with warnings; npm start fails to compile. Alternatively, on a new clone from the master - yarn install works (including deleting the `yarn.lock` file) with warnings; yarn start compiles successfully. This is after you merged a couple of pull requests. i.e Merge pull request #148 from NordicFlyer/master.

FYI, the 2.2.4 Release does not compile via yarn on my machine. i.e aforementioned pull request is not incorporated into the release.

I went to the trouble of reinstalling node js, angular js, typescript, etc. on my Mac to ensure there was not something wonky going on there.

In the final analysis, yarn works for my setup on the current master - good enough for me. Thanks!

**Comment by jimmykane** [comment]
Hi @NordicFlyer  I have solved this issue once and for all. I managed to reproduce this. 

For the reference. When using on package.json git links for packages there is a git cache. 
Despite the commit reference being the same as qslib was the downloaded package differed. 

SQLIB is now published at v3.0.0 and QS depends on it. 

That said it can only happen again if I forget to update the package to the latest version of the qslib that now is a npm module. 

I hope it helps. 

You can now update to latest master/use the repo yarn.lock etc normally. 


Btw Are you interested into knowing how to setup the project on firebase?

**Comment by NordicFlyer** [comment]
That sounds great! Thanks. Yes, I am interested in knowing how to setup the project on firebase - a step by step guide would be useful, i.e. I played around a bit with firebase but just have not had the time to pursue it. Any knowledge you have to offer is always welcome. Cheers.

**Comment by jimmykane** [comment]
I ll try todo that. The only thing that will be difficult is to get a suunto app partner account.

**Comment by NordicFlyer** [comment]
Fair enough. I would imagine that everything would run on firebase except the services without the Suunto Partner account - is that correct? 

I was thinking about setting something up for the non-profit cycling/triathlon clubs in our community. Start out with approximately 10 select users and eventually open it up to the 600+ members. It would be nice to see more graphs in quantified-self from data such as some of those implemented in WK04 and/or GoldenCheetah (GC), i.e. power distribution, power/hr zones, cadence, CP, heart rate to power, etc. All of the aforementioned are applicable to both cyclists and runners. 

I'm not even certain whether these types of metrics are possible within the confines of the application code. An excellent example of the potential of web-based applications, albeit commercial, is [https://www.cyclinganalytics.com].Much of the new stuff on GC is implemented through R or Python. My issue with most of the desktop and web-based "training" applications is that they are commercial in nature - that does not fit well within the model of many non-profits. Open source applications like GC are a godsend to the cycling/triathlon/running/swimming communities. A real-time web-based application like quantified-self has enormous potential to fill a niche. If the code was tied into GC it would be the cat's meow!
