### ISSUE TITLE
Enable SuuntoApp Android JSONs file import

### ISSUE THREAD

**Issue by mff73** [jimmykane/quantified-self#146]
SuuntoApp stores locally in Android some JSON files for each activities sync with Spartan watch.
Currently : one directory with 2 JSONs : Summary.json + Samples.json

**Comment by mff73** [comment]
Hi Dimitrios,
Not urgent request for sure, but extra data are dead in JSON files without a tool like yours.
For Android rooted users like me, i could be great addition for a first step to get them.
Do you need some more Android SA json files ?
As you wrote somewhere, all data are in "SA" cloud and selected data are send to or get by third parties. Any way to get this extra data (GPSaltitude, battery, etc...) synced out of the cloud by any API specific ?

**Comment by mff73** [comment]
Hi,
SA files storage has changed, now in zip files.
Here is one from Android 4.6.0 if needed to help parse it for manual upload in Quantified ;)
Could be very useful for some debug and specific data not parsed through SA direct upload in Quantified. 
[entry_-2126769728_1561878822.zip](https://github.com/jimmykane/quantified-self/files/3353294/entry_-2126769728_1561878822.zip)

**Comment by jimmykane** [comment]
On it hopefully with next release.

**Comment by mff73** [comment]
Dreams come true :) thanks.

**Comment by jimmykane** [comment]
This is fixed here: 
https://github.com/jimmykane/quantified-self-lib/commit/761690024651a646c886cbb4dc433608e16e3806

The zip contains 2 files. One is the summaries and one is the samples. 

The summaries and samples currently cannot be combined, unfortunately. Needs a couple of days of coding to parse the zip , and join the data and then create a compatible format. 

I might look into that. 

However, currently, it will work if you upload the samples.json to the app. 

The deployment should be with v3.9.0 that I plan to release later today or tomorrow depending on the workload and if I find the time today. 

IS that kinda better?

**Comment by mff73** [comment]
Quick look on smarphone, it works ! So COOL. Thks.
More feedback after deeper usage ;) Tks Maestro.

**Comment by jimmykane** [comment]
Clever clever. You used the beta domain! Good job.
