### ISSUE TITLE
Activity name

### ISSUE THREAD

**Issue by bellostom** [jimmykane/quantified-self#151]
After connecting my accounts to SA with QS, the auto sync adds activities with a name of "New Event". Ideally we should have something more descriptive ie activity type_device name

**Comment by suzzlo** [comment]
Manual imports have the same behavior.
Would be great if the name is copied

**Comment by jimmykane** [comment]
@suzzlo  what do you mean with manual import?

**Comment by suzzlo** [comment]
Go to /Services and put there SA activity link and push "import and open"
