### ISSUE TITLE
[beta] Multisport graph issue - 1st section show all 

### ISSUE THREAD

**Issue by Sartoric** [jimmykane/quantified-self#154]
Graph in multisport looks a bit weird.
The first section of a multisport activity seems to show the full graph (including the other sections) while the second looks a bit shorter then expected

![amCharts](https://user-images.githubusercontent.com/6607379/58750202-9fefe680-848f-11e9-82a4-32d9ea84031c.png)

![amCharts (1)](https://user-images.githubusercontent.com/6607379/58750217-d463a280-848f-11e9-97b0-ae58638e981a.png)

**Comment by jimmykane** [comment]
Hmmm can you elaborate? How should it have been? Could I also have a link ?

**Comment by Sartoric** [comment]
Sure.
The activity is a multi-sport one (Walk-Run-Walk) auto-imported from SA
Quantified split it in 3 parts (as expected , as MC)

![Schermata 2019-06-01 alle 23 34 30](https://user-images.githubusercontent.com/6607379/58753848-ef510980-84c5-11e9-8926-c045b006c1b4.png)

So I supposed that each part should show its graph section (HR in the sample img)
It looks ok for the 3rd part (orange one) 
![amCharts (2)](https://user-images.githubusercontent.com/6607379/58753915-fcbac380-84c6-11e9-8ee0-0bbdff08556f.png)

but the first one (purple) shows the complete graph (1st+2nd+3rd parts)
and the 2nd part shows just a partial graph of that section (missing from 12:56->12:59)

Now, to reply to the question "How should it have been?" ... I don't know 😄  
SA shows the activity as a unique one (metrics too), and I don't like it.
MC shows all the sections details, even if the graph is unique (but you can highlight each section) and it's good to me.
The split graph would be good as you can distinguish every single sport/section

Hope it's a bit clearer now 😁

**Comment by jimmykane** [comment]
can you give me the fit file ?

I am still confused a bit , and need to run it locally :-)

**Comment by jimmykane** [comment]
Oh one more thing. Does resizing the window of the browser help (reminds me
of an old bug)

**Comment by Sartoric** [comment]
> I am still confused a bit , and need to run it locally :-)
😄 

Resizing the browser doesn't change the graph
I've sent the fit via email

**Comment by jimmykane** [comment]
Found the issue. I understand now it was not visible on the screens above. I ll look into it. 

Just FYI, if I release a fix that requires re-parsing you can use the history import. Its designed for correcting those bad imports. 

Now to figure out if it's my issue or Suunto app issue ....

**Comment by jimmykane** [comment]
Found the fix as well. Strange. The first activity has no lap data (there should be always 1 lap).

**Comment by Sartoric** [comment]
I'l test another multisport

**Comment by jimmykane** [comment]
No need. :-) Fixing atm

**Comment by jimmykane** [comment]
<img width="991" alt="Screenshot 2019-06-02 at 17 10 57" src="https://user-images.githubusercontent.com/1268723/58763368-15c08480-855a-11e9-9746-1ba3995e73a0.png">
This should look correct right? 
There is one little gap on records is that correct? Did you pause?

**Comment by jimmykane** [comment]
<img width="1438" alt="Screenshot 2019-06-02 at 17 17 52" src="https://user-images.githubusercontent.com/1268723/58763394-620bc480-855a-11e9-90d9-14514b1e2479.png">
Ok got it this should be correct right?

**Comment by Sartoric** [comment]
yes :)
well, in fact if I remember well I paused but just for 10/20 secs 

I noticed that import a fit from MC and auto import from SA generate 2 different results (graph and laps) but maybe you've already fixed it 😄

**Comment by jimmykane** [comment]
Working on it give me a few. Differences can be there from MC and SA as they both produce different fit files

**Comment by Sartoric** [comment]
No problem, don't rush, I'm not in a hurry 😁 😁

**Comment by jimmykane** [comment]
2.7.5-Matt fixes this issue. Reupload is needed. Version is now deployed.
