### ISSUE TITLE
missing font

### ISSUE THREAD

**Issue by tve** [jimmykane/quantified-self#161]
running `yarn start` on a linux box I get the following error (and the same one for the woff2 file):
```
ERROR in ./src/styles.scss (./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/src??embedded!./node_modules/sass-loader/lib/loader.js??ref--13-3!./src/styles.scss)
Module Error (from ./node_modules/postcss-loader/src/index.js):
(Emitted value instead of an instance of Error) CssSyntaxError: /home/tve/Projects/Navigation/quantified-self/stdin:37:2: Can't resolve 'assets/fonts/proxima-nova-regular.woff' in '/home/tve/Projects/Navigation/quantified-self/src'

  35 | @font-face {
  36 |   font-family: 'ProximaNova-Regular';
> 37 |   src: url('assets/fonts/proxima-nova-regular.woff2') format('woff2'),
     |  ^
  38 |   url('assets/fonts/proxima-nova-regular.woff') format('woff');
  39 |   font-weight: normal;
``

**Comment by NordicFlyer** [comment]
> running `yarn start` on a linux box I get the following error (and the same one for the woff2 file):
> 
> ```
> ERROR in ./src/styles.scss (./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/src??embedded!./node_modules/sass-loader/lib/loader.js??ref--13-3!./src/styles.scss)
> Module Error (from ./node_modules/postcss-loader/src/index.js):
> (Emitted value instead of an instance of Error) CssSyntaxError: /home/tve/Projects/Navigation/quantified-self/stdin:37:2: Can't resolve 'assets/fonts/proxima-nova-regular.woff' in '/home/tve/Projects/Navigation/quantified-self/src'
> 
>   35 | @font-face {
>   36 |   font-family: 'ProximaNova-Regular';
> > 37 |   src: url('assets/fonts/proxima-nova-regular.woff2') format('woff2'),
>      |  ^
>   38 |   url('assets/fonts/proxima-nova-regular.woff') format('woff');
>   39 |   font-weight: normal;
> ``
> ```

See my comments on #162. Thanks.

**Comment by jimmykane** [comment]
Thanks looking into it

**Comment by jimmykane** [comment]
This is a tricky one. This font is licensed so I could not source control it. 
I have to think about a workaround for this. Probably will take a few as I need to perhaps change this at build time. 
Suggestions are open @NordicFlyer @tve

**Comment by suzzlo** [comment]
Use an alternative?
https://w3bits.com/proxima-nova-alternative-fonts/

Lato looks good and it's Open Font License - https://fonts.google.com/specimen/Lato

**Comment by jimmykane** [comment]
Agreed lets do that. I ll hack this one for now and just rename lato to proxima  so I dont have to setup githooks etc.

**Comment by suzzlo** [comment]
Hi, I have created a branch, added new Lato font (woff and woff2) and changed all styles.
Then I tried to push my branch (to create a pull request), but permission denied...
Obviously, I don't want to push to master or develop branches, but no idea how to contribute (first contribution in github)

BR

**Comment by Djailla** [comment]
@suzzlo you need to create a fork for this

Check this doc :

https://blog.scottlowe.org/2015/01/27/using-fork-branch-git-workflow/

**Comment by jimmykane** [comment]
v3.8.3 is out now. When the font is missing it should fallback to Roboto that looks okish. 

@NordicFlyer  a test and confirmation would be appreciated.
