### ISSUE TITLE
upload does not work

### ISSUE THREAD

**Issue by tve** [jimmykane/quantified-self#162]
I tried to upload a FIT file and a GCX file produced from a Gramin Edge 130 and neither shows up in the list of activities after upload. I see "uploading 0 of 1 files" at first, then the "processed 1 file" notification at the bottom, but the activities list continues to say "nothing to show" even if I select "all". I tried https://quantified-self.io as well as a local install. I see no errors and no error log anywhere. How would I troubleshoot? (I can provide the files I uploaded privately.)

(All this also raises the question what does this project actually do? I've now spent at least 20 minutes and still don't really know whether it fits my needs. Maybe it would be worth it to post a few screenshots that describe the features...)

**Comment by NordicFlyer** [comment]
Dimitrios Kanellopoulos, the author of this project, has posted a bunch of pertinent information here: 
[](https://forum.suunto.com/topic/520/additional-external-tools/200)

The site [](https://quantified-self.io) does not appear to be working properly at the moment.

I ran into the same errors as you building the project master locally on macOS. The last known release that compiled successfully on my mac was 2.2.12-NordicFlyer. I hope this helps.

**Comment by NordicFlyer** [comment]
> I tried to upload a FIT file and a GCX file produced from a Gramin Edge 130 and neither shows up in the list of activities after upload. I see "uploading 0 of 1 files" at first, then the "processed 1 file" notification at the bottom, but the activities list continues to say "nothing to show" even if I select "all". I tried https://quantified-self.io as well as a local install. I see no errors and no error log anywhere. How would I troubleshoot? (I can provide the files I uploaded privately.)
> 
> (All this also raises the question what does this project actually do? I've now spent at least 20 minutes and still don't really know whether it fits my needs. Maybe it would be worth it to post a few screenshots that describe the features...)

Dimitrios Kanellopoulos, the author of this project, has posted a bunch of pertinent information here:
https://forum.suunto.com/topic/520/additional-external-tools/200

The site, https://quatified-self.io,  does not appear to be working properly at the moment.

I ran into the same errors as you building the project master locally on macOS. The last known release that compiled successfully on my mac was 2.2.12-NordicFlyer. I hope this helps
