### ISSUE TITLE
Walking Sport type is not recognized

### ISSUE THREAD

**Issue by suzzlo** [jimmykane/quantified-self#163]
Walking activities are not recognized

![image](https://user-images.githubusercontent.com/105657/59613776-c5cbeb00-911f-11e9-9925-04d73c7afd56.png)

BR

**Comment by jimmykane** [comment]
Hey! Could I have a link to that (don't forget to make it public by clicking the lock icon and then sharing the url). 

I did a fix today at least that should work for new ones but I might be able to fix the old ones as well.

**Comment by suzzlo** [comment]
Sure

https://quantified-self.io/user/AKHBtogw4QMwYmVZ0GrXMQPMayz1/event/3cPQA91MbTn2CvY9kk3KAi6KrRUveso6wzHuYZk1PgLo1zy

Did you need SA link?

**Comment by jimmykane** [comment]
This will do

**Comment by jimmykane** [comment]
Should be fixed for all new imports/syncs. 

You can if you like redo a history import and that should fix it.

**Comment by suzzlo** [comment]
Yeah!!

Thanks.
