### ISSUE TITLE
Activity import: Squash activities are imported as Generic

### ISSUE THREAD

**Issue by suzzlo** [jimmykane/quantified-self#167]
Like Martial Arts activities, Squash is being imported as generic

**Comment by jimmykane** [comment]
Link please ?

**Comment by suzzlo** [comment]
Sorry....

SA: https://app.suunto.com/move/suzzlo/5c476a548bfe5d6ed2786074

QS: https://beta.quantified-self.io/user/AKHBtogw4QMwYmVZ0GrXMQPMayz1/event/dJHjPCKVDpVUQwDegTFM
