### ISSUE TITLE
EPOC graphs are not working

### ISSUE THREAD

**Issue by suzzlo** [jimmykane/quantified-self#169]
Hi,

In the dashboard graphics, EPOC could not be used, because of erroneus calc?

![image](https://user-images.githubusercontent.com/105657/61513387-330fbc00-a9fd-11e9-9c84-2d364eeaaba2.png)

**Comment by jimmykane** [comment]
Hey thanks. I'll take a look into it.

**Comment by jimmykane** [comment]
YEah here is the issue @suzzlo 

EPOC is a datatype coming from Suunto JSONS. 
Peak Epoc is what Suunto exports to FIT files or uses with SA

Selecting PEAK Epoc should do the trick. 

The chart is broken at EPOC selection because there are no epoc data. Only Peak epoc. Makes sense?

**Comment by suzzlo** [comment]
Uhmmm, so this data is in JSON but not in FIT file? ok... understand, but for the user it's a bit crazy...

Same happens with:
* Peak Training Effect
* VO2Max (since I have no watch with VO2Max estimation) :-(

BR

**Comment by jimmykane** [comment]
Yes indeed it is confusing. Perhaps remove those JSON values there so the user wont get confused? 

OR append them Suunto JSON ? 

Ideas?

**Comment by jimmykane** [comment]
Info on our forum :-D https://forum.suunto.com/post/33052
