### ISSUE TITLE
GPX Distance showing zero

### ISSUE THREAD

**Issue by Pieter-ZA** [jimmykane/quantified-self#173]
Just a note - distance shows 0 when importing Garmin Connect (& Strava) GPX files.  
TCX imports from orig platform is fine though.

**Comment by jimmykane** [comment]
Hey thanks! Could you provide a file as an example ? (TCX)

**Comment by Pieter-ZA** [comment]
Hello!
PFA as requested.
Thanks 

[Tour_de_Krans_D1.zip](https://github.com/jimmykane/quantified-self/files/3491933/Tour_de_Krans_D1.zip)

**Comment by jimmykane** [comment]
Hey sorry for not getting back to this. From the zip I get: 

TCX OK 
<img width="693" alt="Screenshot 2019-08-30 at 23 53 25" src="https://user-images.githubusercontent.com/1268723/64053129-6c515500-cb81-11e9-8b78-b2d3c0adaa3f.png">


Strava 
<img width="958" alt="Screenshot 2019-08-30 at 23 54 40" src="https://user-images.githubusercontent.com/1268723/64053173-90149b00-cb81-11e9-8be5-ce4cd5ed0015.png">


And Garmin Connect 

<img width="965" alt="Screenshot 2019-08-30 at 23 55 27" src="https://user-images.githubusercontent.com/1268723/64053206-ad496980-cb81-11e9-9287-3839b46e4697.png">

All looks good to me

**Comment by Pieter-ZA** [comment]
Many thanks for your trouble Dimitrios, much appreciated - will check again
:)
