### ISSUE TITLE
The total average HR is summed instead of averaging

### ISSUE THREAD

**Issue by lajosh** [jimmykane/quantified-self#174]
The chart showing average heart rates per sport shows the sum of the per-sport values instead of the average.
![avg_hr](https://user-images.githubusercontent.com/54703733/64003871-7e91ab80-cb0d-11e9-8816-fda2e35cf748.png)

**Comment by lajosh** [comment]
Seems to be an issue with aggregation in general. This is the "last month" view:
![hr_aggr](https://user-images.githubusercontent.com/54703733/64004874-789cca00-cb0f-11e9-9282-8e99e8b324e5.png)

**Comment by jimmykane** [comment]
Hmmm. 

I think you want to change the total to average or maximum 

See here 
<img width="929" alt="Screenshot 2019-08-30 at 12 01 59" src="https://user-images.githubusercontent.com/1268723/64012446-07b0de80-cb1e-11e9-8ed3-e6b3f283a932.png">


Right?

**Comment by jimmykane** [comment]
So it kinda works like: 

Select the metric eg: Max/Min/AVG 

The select the aggregation: Sum (total), AVG , Min, Max 

Of course it does not make so sense to see the total maximum heart-rate. 

But the AVerage maximum HR makes a bit of sense. 

You can also eg select the max of the max eg like here: 

<img width="729" alt="Screenshot 2019-08-30 at 12 06 23" src="https://user-images.githubusercontent.com/1268723/64012766-9b82aa80-cb1e-11e9-8c5b-7b7778f81dfa.png">

The above will show eg per sport what was the max HR reached

**Comment by lajosh** [comment]
Aggregation function is configurable, not a bug.

**Comment by jimmykane** [comment]
Perfect. More choices to come are under development FYI
