### ISSUE TITLE
Vertical Speed = 0 for descent

### ISSUE THREAD

**Issue by mff73** [jimmykane/quantified-self#175]
Hi Dimitrios,

Descent for my recent activities synced from SA (auto sync) shows 0.
But if android json is imported : correct vertical speed
From SA auto sync : 
![image](https://user-images.githubusercontent.com/50132146/64072544-c3921b00-cc90-11e9-919b-44c2c78d7cdd.png)
From json import
![image](https://user-images.githubusercontent.com/50132146/64072557-03590280-cc91-11e9-8291-ff9cdc4fc768.png)

SA link
https://www.sports-tracker.com/workout/mff440/5d59606858e2116a0148f21e

**Comment by jimmykane** [comment]
Should be fixed at 4.6.0-Matt that is released currently. 

Note: You need to redo a history import to get those corrected. Fix was also done via the Suunto API ZONE
