### ISSUE TITLE
Tennis activity reported as Soccer

### ISSUE THREAD

**Issue by markusklopf** [jimmykane/quantified-self#176]
All my Tennis activities are reported as "Soccer".

My tools:
- Recording via Suunto 9 Baro, using Tennis activity mode
- Properly shown in Suunto App and Sports Tracker

**Comment by jimmykane** [comment]
Should be fixed now

Thanks for reporting this @markusklopf , unfortunately the data type is persisted which means that you will have to reimport those activities
