### ISSUE TITLE
Select/unselect activities to be included in statistical charts

### ISSUE THREAD

**Issue by NordicFlyer** [jimmykane/quantified-self#177]

**Comment by NordicFlyer** [comment]
To me, the most useful feature in quantified-self is the ability to merge and compare activities from different devices. I often record a cycling activity with both a Joule GPS on my bike and a Suunto watch (as a backup). It is useful in determining the strengths and weaknesses of the data recorded by the Suunto watch. Unfortunately, including duplicate activities and a merge of the aforementioned activities just skews the metric totals within the charts. Is there any way to exclude certain activities from being included in the totals? It is a real pain to got back and delete all duplicates and merges. I have a attached a chart to better illustrate my feature request.
![Screen Shot 2019-09-23 at 10 38 55 AM](https://user-images.githubusercontent.com/9980081/65446153-014a1580-ddf1-11e9-9271-07b654ff7849.png)

**Comment by jimmykane** [comment]
I am sure i had made that merges do not appear in the summaries. Are you
sure ?

(Else its a bug)

**Comment by NordicFlyer** [comment]
> I am sure i had made that merges do not appear in the summaries. Are you sure ? (Else its a bug)
> […](#)

You are absolutely correct. If I delete one of my parallel activities from an alternate device, the totals in the charts are correct. Activity merges are NOT included in the totals. I can live with that! Thanks...consider the issue closed.
