### ISSUE TITLE
Perceived exertion drop-down list is not sorted by numeric values

### ISSUE THREAD

**Issue by okaydoubleu** [jimmykane/quantified-self#178]
In the event-table, the "Perceived exertion" drop-down list is currently sorted as text and not as numeric value. Hence "10 Maximal" comes in between "1" and "2".
![2019-10-07 10_36_38-Dashboard - Quantified Self](https://user-images.githubusercontent.com/20895245/66281571-843d9680-e8ee-11e9-9ecb-00916452d991.png)

**Comment by jimmykane** [comment]
Hey @okaydoubleu thanks for reporting this. 

Looks like the keyvalue pipe of angular does it's own sorting. (I had that enum sorted correctly) 

66c096bbf13b95e39f42f2c55ac48db3c69c121d should fix this and it's being deployed atm with v4.7.5
