### ISSUE TITLE
Offset merged activities

### ISSUE THREAD

**Issue by garagenisse** [jimmykane/quantified-self#186]
Hi, i use this excellent tool to compare poweroutput from two different sources. This works well but for some reason the sources are a bit offset in respect to eachother. Is there a way to fiddle with this so the graphs overlay a bit better? I provided an image that examplifies my problem a bit.

Regards Andreas

![image](https://user-images.githubusercontent.com/3446623/71154652-4ccb5e80-223c-11ea-9465-c0f53837efae.png)

**Comment by jimmykane** [comment]
Hey @garagenisse  I think that is already possible. 

There are 2 options here. 

As you have in this screenshot the axis is based on time , which should be the best to kinda align the stamps. 

However, minor offsets can be there for various reasons. 

To fix this you can press edit on the activity like here: 

<img width="1429" alt="Screenshot 2019-12-19 at 09 56 52" src="https://user-images.githubusercontent.com/1268723/71159449-f2cf9680-2245-11ea-847d-6b82bd893967.png">

Then you will be able to offset the start time like this 

<img width="1065" alt="Screenshot 2019-12-19 at 09 57 10" src="https://user-images.githubusercontent.com/1268723/71159481-00851c00-2246-11ea-9270-8b18dcc49e04.png">



I suggest offseting it for a few seconds and that should fix this .
