### ISSUE TITLE
Recommend switch to a standard OSS license

### ISSUE THREAD

**Issue by truedat101** [jimmykane/quantified-self#187]
Thanks by the way, for the awesome project and contribution to OSS.  I was reviewing the license.  It looks like an MIT/X derived license, similar to a JSON and JSLint license out there.  For whatever reason, the "good / evil" statement makes the license non-free.  Reviewing comments here: https://en.wikipedia.org/wiki/JSLint I was surprised .  I see similar comments about the same license on debian lists.  I understand the intent.  Perhaps there is a better license to reflect the sentiment of data privacy, if that was the author's intent in choosing this license.  Looking forward to trying out the software for myself.

**Comment by jimmykane** [comment]
Hey @truedat101  thanks a lot for opening this issue. 

Indeed this needs to be changed. 

Perhaps a little history on the current licence selection decision. 

I had always been fascinated by the "ibm and its minions" quote and at the time of creating this project I assumed this would protect it from a company using this or a person offering a service but mainly for 2 reasons. 

a) Company wise I didn't want any interaction
b) Individual wise the project was not ready to be "forked" distributed etc 

However, the project reached version 5 which was it's initial target. 

I am currently at the process of actually documenting, refactoring, and making this something "more open" rather than a fast development project (MVP) just to reach "its target" 

I will be changing the license as well. 

I am open to any suggestions and would love to hear your opinion.

**Comment by jimmykane** [comment]
Hi @truedat101 . Do you have a type of license to recommend? 

I will be doing this in the next days

**Comment by jimmykane** [comment]
@DoPaNik @zacchiro @simonech any suggestions / recommendations ?

**Comment by zacchiro** [comment]
Thanks for the ping @jimmykane ! I didn't notice the "no evil" bit in the license, and I agree it's an issue that might impact adoption. You definitely want to pick a license that is approved by both OSI and FSF.

Beyond that, it really depends on the kind of governance you want to have for quantified self.

My personal preference is for ecosystems in which all players share on equal grounds, i.e., if someone benefits from your software and modifies it, they should share their modifications with you and everyone else. That is, a copyleft license. For an app which is primarily web-based, the most appropriate copyleft license is [AGPL](https://www.gnu.org/licenses/agpl-3.0.en.html). With AGPL if someone hosts a modified version of quantified self, they should give access to the source code of their version to all users.

If you don't care about others modifying your code without sharing their modifications with the community, a modern permissive license (similar to what I _think_ you wanted to have with the current MIT-like text) that would fit the bill is [Apache 2](https://www.apache.org/licenses/LICENSE-2.0).

**Comment by simonech** [comment]
I’ve seen most projects use a MIT license. 
The GPL like are bit too restrictive imho

**Comment by DoPaNik** [comment]
Thanks @jimmykane for asking. In general I am a fan of the WTFPL. But it makes sense to license the project under an AGPL to benefit from each other. That should be self-evident, but unfortunately it is not! 

so much about my view on it ;-)

**Comment by truedat101** [comment]
Sorry late reply @jimmykane  , Apache license would work well.  *GPL tends to freak out companies who might use the software, and some people who don't like the license.  As a person who has spent a bunch of time guiding companies who are taking commercial projects into Open Source, I will usually make a comment on this point for projects that have promise and are missing a license or have adopted something that might be a problem.  Thanks for following up on this.   

As an option, you can always reserve the right to dual license your software and let recipients of the software choose. Assuming you are the sole copyright holder, then it is an easy change.  If you have accepted contributors and they haven't signed a CLA, then it would require permission from your contributors.  The case for a dual license is typically : get your GPL (with copyleft provisions) or get your commercial / proprietary license (unrestricted, probably with some money involved).   There is no reason you couldn't keep your original license and also offer an MIT/X or Apache license.

**Comment by jimmykane** [comment]
Went with AGPL v3 I hope that is ok with you all guys
