### ISSUE TITLE
Orienteering imported from Suunto App as trail running

### ISSUE THREAD

**Issue by trsqr** [jimmykane/quantified-self#188]
I just connected Suunto app to Quantified Self and performed a historical import for my 2019 activities. For some reason my orienteering activities got imported as trail running activities. My trail running activities were correctly imported as trail running. Now I just cannot make a difference between them very easily.

**Comment by jimmykane** [comment]
Hey we can fix this once I identify the problem with another history import
(there is no duplication )

Could you provide via email at jimmykane9@gmail.com  a corresponding Suunto
app link with the type of orienteering?

I'd be glad to fix that for you.

**Comment by trsqr** [comment]
Thanks for a quick response. Just sent you a link to one activity that got imported as trail running. I've now manually changed the activities in Quantified Self to correct type, but I suppose someone else might want to import their orienteering activities.

**Comment by jimmykane** [comment]
That should be fixed now
