### ISSUE TITLE
Hide ascent of activity type

### ISSUE THREAD

**Issue by asorli** [jimmykane/quantified-self#190]
Activities in filter "Hide ascent of activity type"
![2020-02-11 14_08_27-Window](https://user-images.githubusercontent.com/34653992/74239462-2bd13800-4cd8-11ea-95eb-13f28c733c90.png)

are excluded from all totals.

![image](https://user-images.githubusercontent.com/34653992/74239599-72269700-4cd8-11ea-9e9c-091c77487667.png)

**Comment by jimmykane** [comment]
Hi thanks for this. Indeed this is a mistake / bug 

Thanks for this. I ll be fixing this asap.

**Comment by jimmykane** [comment]
This should be fixed in `5.5.24-Bisbiki` that is released now :-D 

Thanks for reporting this and feel free to check if its ok

**Comment by asorli** [comment]
Rapid fix. Work's fine now.
