### ISSUE TITLE
Export of .FIT file that includes all training metrics including Training Effect and Epoc: Feature Request

### ISSUE THREAD

**Issue by NordicFlyer** [jimmykane/quantified-self#195]
I would prefer that all personal training data is not locked into the Quantified-Self application (except for JSON download) and all metrics enabled to be exported into a .FIT file like Suunto's mobile application. Like many others, I use my laptop to analyze data on a larger screen. I also use many other applications like Golden Cheetah, Strava, Garmin Connect, TrainingPeaks, etc., and would like easy access to all the data from my Suunto Spartan Trainer. I love your open-source application but would prefer that the data is not locked in. The JSON file is not suitable for importing to other applications for planning and analysis. Suggestions? Moving back and forth between a phone/tablet and a desktop/laptop is time consuming. Valuable time the I would rather spend cycling, hiking, skiing, and so forth. Cheers!

**Comment by jimmykane** [comment]
Would you like to download directly from the SA server per activity or do you think the QS should store those files (original) to its own bucket?

**Comment by NordicFlyer** [comment]
> Would you like to download directly from the SA server per activity or do you think the QS should store those files (original) to its own bucket?

Good question. Downloading from the SA server per activity within QS is useful. However, emailing or texting myself a link from the Suunto App on my device(s) and then coping and pasting into QS on a laptop browser is inconvenient. Is there a simpler way to access my data directly from the SA server via a laptop browser? When it comes to non-Suunto products, it might be preferable for QS to store original files and allow various download options similar to Suunto's Movescount - assuming server space and load is not an issue. As an example, I still simultaneously record my cycling data via bluetooth with my Suunto Spartan and Ant+ on a Joule GPS. Comparing that data on QS clearly reveals the strength and weaknesses of different devices and bluetooth vs. Ant+ protocols. It has also proven to be a good back-up plan when one device fails to record data properly. Thanks for your response. Cheers!

**Comment by jimmykane** [comment]
This should come with the next release. 

There will be a button that allows you to download the activity from a service (that now being Suunto app) once you have opened it. 

It will request the original file from the service. QS wont be storing atm and intermediate files. 
If there is enough support on https://www.patreon.com/dimitrioskanellopoulos for QS I will be able to enable the FIT file storage on QS , extraction as ZIP etc. 

Please consider supporting

**Comment by jimmykane** [comment]
This is now deployed
