### ISSUE TITLE
Can't merge several activities

### ISSUE THREAD

**Issue by risbac** [jimmykane/quantified-self#205]
Hi! 

I tried on Chrome & Firefox, with 4 activities, then just 2. From different days. It's not working anymore. The list is greyed out, and nothing happens. It's failing with activities I successfully merged a few days ago.

**Comment by jimmykane** [comment]
Hey what version are you using?

I have it a try now quickly before my run and works.

Latest version is 6.2.14

**Comment by risbac** [comment]
I can confirm, 6.2.14, and it's still failing. Tried again just now, still
the same; I see the line with the scrolling dots, but it stays like that
forever.

**Comment by jimmykane** [comment]
Could you try :

Another browser ?

Sending me the fit files ?

There is a case that if a file is kinda corrupt , it can be parsed but it
cannot be merged.

You can also email the files if you worry about privacy posting them here.

**Comment by jimmykane** [comment]
This should be solved
