### ISSUE TITLE
Migrate to GitHub actions 

### ISSUE THREAD

**Issue by jimmykane** [jimmykane/quantified-self#212]
Migrate build and deploy to GitHub actions.

**Comment by DoPaNik** [comment]
Are there any special requirements?

**Comment by jimmykane** [comment]
Hi @DoPaNik  I think nothing more than issuing a build and deploying to firebase. 

Previously it was using travis , but that broke at some point and deployments are now done by me, which is not so good after all. Creates the risk of using my local module cache, especially when switching branches that have different / updated dependencies.

**Comment by DoPaNik** [comment]
I'll take a look.

**Comment by jimmykane** [comment]
Hey thank you @DoPaNik 

If you need any collab permission here I have no issues giving such :-) 

Even if temporarily

**Comment by DoPaNik** [comment]
Hey and thanks @jimmykane, at the moment i don't know exactly where I might need permissions. Haven't done anything with firebase before and have a look at it for now. I'll get back to you.

**Comment by jimmykane** [comment]
Yeah I am not sure as well, just wanted to say a heads up if you need anything. 

In theory from what I had searched in the past, github actions should have an action for firebase deploy.  Just saying
