### ISSUE TITLE
quantified-self as a part of hacktoberfest

### ISSUE THREAD

**Issue by DoPaNik** [jimmykane/quantified-self#215]
Project in the context of the Hackoberfest for community growth?
I suspect that the project could benefit from this - what do you think?

 https://hacktoberfest.digitalocean.com/hacktoberfest-update

Now Hacktoberfest-Opt-in required for projects! Public projects are no longer automatically included.

**Comment by jimmykane** [comment]
Done

**Comment by jimmykane** [comment]
Spread the word !
