### ISSUE TITLE
Dashboard filter not working

### ISSUE THREAD

**Issue by andreamusso2020** [jimmykane/quantified-self#229]
Both time filtering and activity filtering are not working in dashboard. In any selection the activity showed in the map and graph remain all.

Borwser used chrome.

**Comment by jimmykane** [comment]
Should be fixed with v6.13.1 keep my posted if you have issues.  

Thank you so much for the report.

**Comment by andreamusso2020** [comment]
Tks. The preset filters are working now but not the custom.

It looks like the better tool there is around. I'll try I little and if
confirmed the impression I'll support for sure!

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Mail
priva di virus. www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Il giorno mer 17 feb 2021 alle ore 19:41 Dimitrios Kanellopoulos <
notifications@github.com> ha scritto:

**Comment by jimmykane** [comment]
Feel free to reopen this.
